@startuml
'https://plantuml.com/sequence-diagram
hide footbox
actor ChairPerson as ChairPerson
participant view as view
participant Controller as Controller
participant courseCatalogue as courseCatalogue
participant Course as Course
loop until exit
ChairPerson -> view: click add course button
view -> Controller: add course
Controller -> courseCatalogue **: addCourse()
Controller -> view: return course list
view -> ChairPerson: display course list
courseCatalogue -> Course **: addCourse(id, time)
end
loop until exit
view -> Controller: remove course
Controller -> courseCatalogue: removeCourse()
courseCatalogue -> Course: removeCourse(id)
Controller -> view: return course list
view -> ChairPerson: display course list
end
@enduml