@startuml
'https://plantuml.com/sequence-diagram
hide footbox
actor AdvisorPerson as AdvisorPerson
participant Controller as Controller
participant Advisor as Advisor
participant Advisee as Advisee

AdvisorPerson -> Controller: add advisee
AdvisorPerson -> Controller: remove advisee
AdvisorPerson -> Controller: return advisee list
Controller -> Advisor **: create()
Controller -> AdvisorPerson: get advisee info
Controller -> Advisor: add advisee
Controller -> Advisor: remove advisee
Controller -> Advisor: return advisee list
Advisor -> Advisee **: create (name, id, year)


@enduml