@startuml
skinparam classAttributeIconSize 0

class CourseCatalogue{
Hashmap: courseCatalogue
--
+addCourse()
+getCourseCatalogue
+removeCourse()
+returnCourseList()
+size()
+inCatalogue()
+get()
+editTime()
}

class Course{
String: id "CS203"
String:time
ArrayList:prerequisites
--
+getId()
+getTime()
+getPrerequisites()
+equals()
+toString()
}

class Advisor{
Hashmap advisees
--
+addAdvisee()
+adviseeNames()
+returnAdviseeIds()
+deleteAdvisee()
+returnAdviseeList()
+size()
+getAdvisee()
+getAdviseeID()
+addClassTaken()
}

class Advisee{
String: advisor
String:name
int: id
int: classYear
List: classesTaken
String Major
--
getName()
getId()
getClassYear()
getClassesTaken()
getClassesNeeded()
getMajor()
getAdvisor()

}

class Major{
Hashmap:Major pools
--
+createPool()
+addCourse()
+getMajor()
+setRequiredPoolCourses
+removeCourse
+getPools()
+getAPool()
+hasPool()

}
class Pool{
int numRequiredCourses
ArrayList poolList
String poolName
--
+Pool()
+getNumOfRequiredCourses()
+getpoolList()
+getpoolName()
+addPoolCourse()
+removePoolCourse()

}

class ControllerActivity{

}

CourseCatalogue *- Course
Advisor *- Advisee
ControllerActivity *- CourseCatalogue
ControllerActivity *- Advisor
Major *- Pool
ControllerActivity *- Major
@enduml


