@startuml


package "AcademicAdivsor"{
  (See requirement checklist) as (check-major-requirments)
  (Enter Courses) as (enter-courses)
  (Manage Advisees) as (manage-advisees)
  (Manage Schedule) as (scheduling)
  (Enter Major Requirement) as (enter-major-requirement)
}

Advisee --> (check-major-requirments)
Adivser --> (check-major-requirments)
departmentChair --> (check-major-requirments)
departmentChair --> (enter-major-requirement)
Advisee --> (enter-courses)
Adivser --> (enter-courses)
Advisee --> (scheduling)
Adivser --> (scheduling)
Adivser --> (manage-advisees)
@enduml ```
