@startuml
'https://plantuml.com/sequence-diagram
hide footbox
actor ChairPerson as ChairPerson
participant Controller as Controller
participant courseCatalogue as courseCatalogue
participant Course as Course

ChairPerson -> Controller: add course
ChairPerson -> Controller: remove course
ChairPerson -> Controller: return course list
Controller -> courseCatalogue **: create()
Controller -> ChairPerson: get course info
Controller -> courseCatalogue: add course
Controller -> courseCatalogue: remove course
Controller -> courseCatalogue: return course list
courseCatalogue -> Course **: create (id, time)

@enduml