@startuml
skinparam classAttributeIconSize 0

class CourseCatalogue{
--
+makeCourse()
+addCourse()
+listCourse()
}

class CourseObj{
String: id "CS203"
String:time
}

class AdviserObj{
}

class AdviseeList{
--
+addAdvisees()
+addCourses()
}

class AdviseeObj{
String:name
int: 999
int: class year
}

CourseCatalogue *- CourseObj
AdviserObj *- " advisee list {ordered list}" AdviseeList: \t \t\t  \t \t
AdviseeList *- AdviseeObj

@enduml

case 1: new
