@startuml
skinparam classAttributeIconSize 0

class CourseCatalogue{
--
+addCourse()
+removeCourse()
+returnCourseList()
}

class Course{
String: id "CS203"
String:time
}

class Advisor{
--
+addAdvisee()
+deleteAdivsee()
+returnAdviseeList()
}

class Advisee{
String:name
int: id
int: classYear
}

CourseCatalogue *- Course
Advisor *- Advisee
Controller *- CourseCatalogue
Controller *- Advisor

@enduml

case 1: new
