@startuml
'https://plantuml.com/sequence-diagram
hide footbox
actor DepartmentHead as DH
participant CourseController as CO
participant CourseObj as COO
participant CourseCatalog as CC

DH -> CO: make course
CO -> DH: ask for next course
CO -> COO: make(id, time)
COO -> CO: get next
COO -> CC: add(courseObj)
CC -> COO: get next course



@enduml