@startuml
'https://plantuml.com/sequence-diagram
hide footbox
actor DepartmentHead as DH
participant courseObj as CO
participant courseCatalog as CC

DH -> CO: make course(id, time)
CO -> DH: ask for next course
CO -> CC: add(courseObj)
CC -> CO: get next course

@enduml