@startuml

package "AcademicAdvisor"{
  (See requirement checklist) as (check-major-requirements)
  (Enter Courses) as (enter-courses)
  (Manage Advisees) as (manage-advisees)
  (Manage Schedule) as (scheduling)
  (Enter Major Requirement) as (enter-major-requirement)
}

Advisee --> (check-major-requirements)
Advisor --> (check-major-requirements)
departmentChair --> (check-major-requirements)
departmentChair --> (enter-major-requirement)
Advisee --> (enter-courses)
Advisor --> (enter-courses)
Advisee --> (scheduling)
Advisor --> (scheduling)
Advisor --> (manage-advisees)
@enduml ```
